export type TelemetryEventName = string;
export type TelemetryProperties = Record<string, unknown>;

export interface TelemetryCaptureOptions {
  debounceMs?: number;
  debounceKey?: string;
  immediate?: boolean;
  /** Allows an event generated by an explicit user submission, such as feedback. */
  explicitUserAction?: boolean;
}

export interface SystemInfo {
  os?: string;
  arch?: string;
}

export interface QueuedTelemetryEvent {
  event: TelemetryEventName;
  properties: TelemetryProperties;
  createdAt: string;
  explicitUserAction?: boolean;
}
